loop through vertices instead of faces
runejs/filestore pull request #17
Opened 2021-04-04 21:27 UTC by hallowatcher

Some vertices were missing when rendering objects. This is because it was looping through the faceCount instead of the vertexCount. I compared the function to the one in the client and the client also loops through the vertexCount, so I assume it was just a mistake when writing out the decoded function :D

2021-04-04 21:31 UTC, Displee commented
I made a bad mistake there. Good find.

2021-04-04 21:32 UTC, Displee approved these changes
Good find.

2021-04-05 01:49 UTC, hallowatcher commented
added a fix to vertex normals for shading

2021-04-05 13:49 UTC, Displee requested changes
You added lots of `~~`. I'm not sure why as they don't do anything?

2021-04-05 14:12 UTC, hallowatcher commented
> 
> 
> You added lots of `~~`. I'm not sure why as they don't do anything?

They are used to remove decimals from a number (converting them to int)

It's the same as `Math.trunc()`, but apparently a bit more performant
![image](https://user-images.githubusercontent.com/6265839/113583189-9efae380-9629-11eb-9389-f783dc1eab36.png)

I guess in the end it doesn't really matter if the number has decimal places or not, but this simulates the RS logic more closely because RS uses java ints which do this automatically

2021-04-05 14:22 UTC, SchauweM reviewed
On line 60, is `this.texturedFaceTypeIndices` also possible to be undefined? If not, change to strict checking `===`

2021-04-05 14:25 UTC, hallowatcher commented
> 
> 
> On line 60, is `this.texturedFaceTypeIndices` also possible to be undefined? If not, change to strict checking `===`

Double equals for null checking is normally the way to go. See this example:

```
undefined === null; // returns false
undefined == null; // returns true
null == null; // returns true
```

2021-04-05 14:43 UTC, Displee commented
> 
> 
> > You added lots of `~~`. I'm not sure why as they don't do anything?
> 
> They are used to remove decimals from a number (converting them to int)
> 
> It's the same as `Math.trunc()`, but apparently a bit more performant
> ![image](https://user-images.githubusercontent.com/6265839/113583189-9efae380-9629-11eb-9389-f783dc1eab36.png)
> 
> I guess in the end it doesn't really matter if the number has decimal places or not, but this simulates the RS logic more closely because RS uses java ints which do this automatically

Ah. I see. Learned something new :P

2021-04-05 14:43 UTC, Displee approved these changes

2021-04-06 21:09 UTC, Tynarus approved these changes

2021-04-06 21:09 UTC, merged