Feature/load xteas
runejs/filestore pull request #19
Opened 2021-04-08 12:32 UTC by Displee

2021-04-08 12:41 UTC, SchauweM reviewed
Can you remove the `console.log` in run.ts since it's not needed?

2021-04-08 13:18 UTC, Tynarus requested changes

2021-04-08 13:18 UTC, Tynarus commented on src/filestore/stores/region-store.ts
> +        const array = JSON.parse(fs.readFileSync('./config/map-keys.json', 'utf8'));
May want to use the filestore config dir for this so the dir that the keys are stored in can be changed

2021-04-08 23:13 UTC, Displee commented
> 
> 
> Can you remove the `console.log` in run.ts since it's not needed?

You mean the console.warn?

2021-04-09 10:44 UTC, Displee commented on src/filestore/stores/region-store.ts
> +        const array = JSON.parse(fs.readFileSync('./config/map-keys.json', 'utf8'));
You mean `./unpacked`?

2021-04-10 00:36 UTC, Tynarus commented on src/filestore/stores/region-store.ts
> +        const array = JSON.parse(fs.readFileSync('./config/map-keys.json', 'utf8'));
`filestore.configDir` :)

2021-04-10 01:38 UTC, Tynarus commented
> > Can you remove the `console.log` in run.ts since it's not needed?
> 
> You mean the console.warn?

tbh the `run.ts` file is only for development purposes, so whatever is in it is irrelevant - it is excluded from modern published packages

2021-04-10 16:27 UTC, Tynarus approved these changes

2021-04-10 16:27 UTC, merged